Network:
  #Gogoanime Base URL
  base: https://gogoanime3
  domain: net
  #API Consumet for Downloadable links
  consumet: null
  #gogocdn, streamsb, vidstreaming [recommended]
  consumet_video_server: vidstreaming
Video:
  #consumet, built-in [recommended]
  source: built-in
  #1080p, 720p, 480, 360p, best
  quality: best
  #auto, manual
  selection: auto
